#pragma once

#include "cocos2d.h"
#include <vector>

/**
 * @brief Single card entry inside a level configuration file.
 *        Contains position + rank + suit only.
 */
class LevelCardConfig
{
public:
    int cardId;          ///< Logical unique ID generated by loader.
    int cardFace;        ///< CardFaceType enum value.
    int cardSuit;        ///< CardSuitType enum value.
    cocos2d::Vec2 pos;   ///< Initial position inside the scene.

    LevelCardConfig()
        : cardId(-1)
        , cardFace(-1)
        , cardSuit(-1)
        , pos(cocos2d::Vec2::ZERO)
    {
    }
};

/**
 * @brief Static payload of a single level (as defined in JSON file).
 */
class LevelConfig
{
public:
    /** Initial playfield cards. */
    std::vector<LevelCardConfig> playfieldCards;

    /** Initial stack/tray cards. */
    std::vector<LevelCardConfig> stackCards;

    LevelConfig() = default;
};


